//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentType
    {
        public AttachmentType()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.ProductDocuments = new HashSet<ProductDocument>();
            this.ProductAttachmentTypes = new HashSet<ProductAttachmentType>();
            this.AuditTrails1 = new HashSet<AuditTrail>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual ICollection<ProductDocument> ProductDocuments { get; set; }
        public virtual ICollection<ProductAttachmentType> ProductAttachmentTypes { get; set; }
        public virtual ICollection<AuditTrail> AuditTrails1 { get; set; }
    }
}
