//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.Fees = new HashSet<Fee>();
            this.Products = new HashSet<Product>();
            this.MajorCategoryOrderings = new HashSet<MajorCategoryOrdering>();
        }
    
        public int CampaignID { get; set; }
        public string CampaignName { get; set; }
        public int CompanyID { get; set; }
        public string CampaignReason { get; set; }
        public Nullable<decimal> CampaignProductCount { get; set; }
        public string CampaignAccountManagerComments { get; set; }
        public string CampaignMerchandiserComments { get; set; }
        public string CampaignInventoryBuyerComments { get; set; }
        public string CampaignMentorComments { get; set; }
        public string CampaignStatus { get; set; }
        public string CampaignCreatedBy { get; set; }
        public System.DateTime CampaignCreatedOnDate { get; set; }
    
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<MajorCategoryOrdering> MajorCategoryOrderings { get; set; }
    }
}
