//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorCategoryOrdering
    {
        public MajorCategoryOrdering()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
        }
    
        public int ID { get; set; }
        public int SortValue { get; set; }
        public int CampaignID { get; set; }
        public int CategoryID { get; set; }
        public string CategoryRename { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
    }
}
