//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingTier
    {
        public PricingTier()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.Fees = new HashSet<Fee>();
        }
    
        public int PricingTierID { get; set; }
        public string PricingTierName { get; set; }
        public int PricingTierLevel { get; set; }
        public int CompanyID { get; set; }
        public string PricingTierStatus { get; set; }
    
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
    }
}
