//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPRModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public Fee()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
        }
    
        public int FeeID { get; set; }
        public int FeeNameID { get; set; }
        public string FeeType { get; set; }
        public int FeeLevel { get; set; }
        public bool FeeInherited { get; set; }
        public Nullable<int> FeeInheritedFeeID { get; set; }
        public string FeeCalculation { get; set; }
        public Nullable<decimal> FeeAmortizedCharge { get; set; }
        public string FeeAmortizedType { get; set; }
        public Nullable<decimal> FeePercent { get; set; }
        public string FeePercentType { get; set; }
        public Nullable<decimal> FeeDollarAmount { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<int> PricingTierID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductSellPriceID { get; set; }
        public string FeeStatus { get; set; }
    
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Company Company { get; set; }
        public virtual FeeName FeeName { get; set; }
        public virtual PricingTier PricingTier { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductSellPrice ProductSellPrice { get; set; }
    }
}
