//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPR2._0._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeName
    {
        public FeeName()
        {
            this.Fees = new HashSet<Fee>();
            this.AuditTrails = new HashSet<AuditTrail>();
        }
    
        public int FeeNameID { get; set; }
        public string FeeNameName { get; set; }
        public string FeeNameType { get; set; }
    
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
    }
}
