//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPR2._0._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagingType
    {
        public PackagingType()
        {
            this.Products = new HashSet<Product>();
            this.AuditTrails = new HashSet<AuditTrail>();
        }
    
        public int PackagingTypeID { get; set; }
        public string PackagingTypeName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
    }
}
