//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPRModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDecoration
    {
        public ProductDecoration()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
        }
    
        public int DecorationID { get; set; }
        public string DecorationName { get; set; }
        public int DecorationMethodID { get; set; }
        public string DecorationColor { get; set; }
        public string DecorationLocation { get; set; }
        public string DecorationSize { get; set; }
        public string DecorationVendor { get; set; }
        public byte[] DecorationImage { get; set; }
        public string DecorationImageType { get; set; }
        public string DecorationEmbroideryDesignNumber { get; set; }
        public string DecorationEmbroideryStitchCount { get; set; }
        public string DecorationEmbroideryColorWay { get; set; }
        public int ProductID { get; set; }
        public string DecorationStatus { get; set; }
    
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual DecorationMethod DecorationMethod { get; set; }
        public virtual Product Product { get; set; }
    }
}
