//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPR2._0._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSellPrice
    {
        public ProductSellPrice()
        {
            this.Fees = new HashSet<Fee>();
            this.AuditTrails = new HashSet<AuditTrail>();
        }
    
        public int SellPriceID { get; set; }
        public string SellPriceName { get; set; }
        public int SellPriceLevel { get; set; }
        public decimal SellPriceMarginPercent { get; set; }
        public decimal SellPriceMarginDollarAmount { get; set; }
        public decimal SellPriceFinalAmount { get; set; }
        public int ProductID { get; set; }
    
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
    }
}
