//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPRModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorType
    {
        public VendorType()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.Products = new HashSet<Product>();
        }
    
        public int VendorTypeID { get; set; }
        public string VendorTypeName { get; set; }
        public string VendorTypeStatus { get; set; }
    
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
